# Auto-generated by Shelix schedule_workflow — do not edit
# Workflow: debug_logger | Schedule: daily | Created: 2026-02-18 12:06
$ErrorActionPreference = 'Stop'
$errorLog = 'C:\Users\georg\AppData\Local\Temp\shelix_task_errors.log'
try {
    # Dot-source required modules (absolute paths, no $PROFILE dependency)
    $global:ModulesPath = 'C:\Users\georg\Documents\PowerShell\Modules'
    . 'C:\Users\georg\Documents\PowerShell\Modules\ConfigLoader.ps1'
    . 'C:\Users\georg\Documents\PowerShell\Modules\PlatformUtils.ps1'
    . 'C:\Users\georg\Documents\PowerShell\Modules\SecurityUtils.ps1'
    . 'C:\Users\georg\Documents\PowerShell\Modules\CommandValidation.ps1'
    . 'C:\Users\georg\Documents\PowerShell\Modules\SystemUtilities.ps1'
    . 'C:\Users\georg\Documents\PowerShell\Modules\ProductivityTools.ps1'
    . 'C:\Users\georg\Documents\PowerShell\Modules\IntentAliasSystem.ps1'

    Invoke-Workflow -Name 'debug_logger'
} catch {
    "[$(Get-Date)] SHELIX TASK ERROR (debug_logger): $($_.Exception.Message)" | Out-File $errorLog -Append
    "$($_.ScriptStackTrace)" | Out-File $errorLog -Append
}
